### ISSUE TITLE
[Bug] Gimbal lock problem with the camera

### ISSUE THREAD

**Issue by BenjaminSouchet** [substack/brickworld#3]
Hi again,
Another bug I've found is related to the rotation it's called gimbal lock, I assume you doesn't use quaternion to do the rotation of the camera/perpective view so you can have gimbal lock problem. 

Gif Demo :
![bugdemo](https://user-images.githubusercontent.com/17025808/40541771-81132700-601d-11e8-8162-254537a60d94.gif)

**Comment by substack** [comment]
can solve this by clamping the maximum phi to ±(Math.PI*0.5-0.001)

**Comment by substack** [comment]
fixed
